### ISSUE TITLE
rust client/server implement

### ISSUE THREAD

**Issue by yangjun** [rsocket/rsocket#261]
rust client/server implement

**Comment by robertroeser** [comment]
@yangjun is this something you're interested in working on or something you're interested in using?

**Comment by akurdyukov** [comment]
@robertroeser I'm investigating opportunities for creating one. For now I see several ways:

1. Clean room pure Rust implementation. Looks like a quite hard task.
2. Wrapping C++ implementation. rsocket-cpp does not look like a live project.
3. Wrapping JVM implementation with GraalVM. Looks like a kamikaze project because of lots of unstable tech involved.

Maybe there's more clean direction?

**Comment by yschimke** [comment]
The cpp project should be live/maintained, but I suspect is feature complete for what FB needs.  It should be a viable option.

**Comment by jjeffcaii** [comment]
I've started an implementation in Rust. see [https://github.com/jjeffcaii/rsocket-rust/](https://github.com/jjeffcaii/rsocket-rust/) if you are interested.

**Comment by jiraguha** [comment]
@jjeffcaii which option of @robertroeser you took?

**Comment by robertroeser** [comment]
@jjeffcaii There is interest in a rust implementation. I don't know enough rust to tell, but it would be good to have idomatic apis. 

I can move this project to rsocket if there is interest in this project.

**Comment by jjeffcaii** [comment]
I'm a beginner of rust. The implementation of rust is still under active development. But maybe we can move it to RSocket org first. @robertroeser Can you create a repo and let me move it? Thanks!

**Comment by jjeffcaii** [comment]
@jiraguha It's a pure Rust implementation and based on [tokio](https://tokio.rs).

**Comment by robertroeser** [comment]
@jjeffcaii created a rsocket-rust repo https://github.com/rsocket/rsocket-rust

**Comment by OlegDokuka** [comment]
closing this one as it seems to be resolved at this moment
