### ISSUE TITLE
[Question] Routing specification naming.

### ISSUE THREAD

**Issue by ronenhamias** [rsocket/rsocket#263]
Small Question why this specification is named routing?
https://github.com/rsocket/rsocket/blob/master/Extensions/Routing.md

to my understanding its about metadata or headers and routing is just a specific case / header or tag.
is that really aiming only for routing?  

for example it can be used for tracing or other usecases.

**Comment by OlegDokuka** [comment]
See -> https://github.com/rsocket/rsocket/blob/master/Extensions/Tracing-Zipkin.md. There is a separate extension aimed for tracing.

**Comment by nebhale** [comment]
The biggest reason is to provide an explicit location for routing metadata to live. Given many different kinds of metadata packed in with Composite Metadata, there’s a large surface area for mistakes. It’s quite easy to have name conflicts that could lead to mis-routing or even worse, intentional exploits. By bounding a metadata type that contains *only* routing information you provide both a namespace that reduces conflicts and a single place for routers to look for authoritative routing information.

**Comment by ronenhamias** [comment]
clear, thanks!
