### ISSUE TITLE
A suggestion for composite metadata

### ISSUE THREAD

**Issue by linux-china** [rsocket/rsocket#269]
First I think composite metadata is a good design.   For a meta, could we exchange "Metadata Encoding MIME Type" and "Metadata Length".

From  
![image](https://user-images.githubusercontent.com/46711/59155117-b3262780-8a36-11e9-808b-6821e80aaa99.png)

to 

![image](https://user-images.githubusercontent.com/46711/59155115-9d186700-8a36-11e9-9dfd-85a8a21422ab.png)

Why?   length information together(4 bytes) just an Integer, and it's easy for encoding/decoding.    for Well known Mime type, we use byte, and for use defined mime type, an Integer can have all length information for mime type and metadata payload length.

**Comment by nebhale** [comment]
I don't think I follow.  This appears to be an ordering issue rather than any significant change.  Even if you put the two lengths together to an integer, you still have to bitshift to get either part out.  Do you have reason to think that your bitshift is easier?  Note there is [an implementation](https://github.com/rsocket/rsocket-java/pull/635/files#diff-b7f8b2e970a889d158b4353fed3ead42R69) in place that means that it's at least _possible_ in the current form.

**Comment by linux-china** [comment]
@nebhale  got.  we just did some research with IDL languages, such as gRPC and WebIDL(WebAssembly).  No byte just bytes in Protobuf, and byte is available in WebIDL, and just make sure  RSocket friendly to IDL.

**Comment by nebhale** [comment]
I'll admit to not having a good idea how amenable any of this is to IDL languages.  @robertroeser or @rdegnan Any opinions on this?

**Comment by robertroeser** [comment]
@linux-china are you talking about encoding the metadata as protobuf or webIDL? The intent here is this a binary frame.
