### ISSUE TITLE
Stream ID 0 frames prioritization

### ISSUE THREAD

**Issue by OlegDokuka** [rsocket/rsocket#279]
# Motivation 

In many cases, frames prioritization is a challenging task, especially when it comes to the specific application's level requests. However, there is a list of highly important internal, RSocket specific frames, which should be considered as highly prioritized payloads/frames within the RSocket ecosystem. For example, most of the Stream ID 0 frames like KEEPALIVE frame or LEASE brings the most important information about the state of connection/capacity. Therefore, it would make sense to send them with the highest priority or frankly speaking, as soon as possible on the level of certain implementation of RSocket spec.

# Proposal 

I propose to explicitly suggest/recommend in the spec to send Stream ID 0 with the highest priority to ensure that they are delivered with the minimum delay.

Just recently I have created a [PR to RSocket-Java](https://github.com/rsocket/rsocket-java/pull/718) which shows performance impact-less solution for that problem.

**Comment by yschimke** [comment]
My thoughts

1) The spec needs to address stream priorities generally, I guess this is currently "QoS and Prioritization".
2) I think implicit ordering should have previously meant that all frames were sent in generally the order they were received at the duplex connection level.
3) If we prioritise Stream ID 0 traffic, effectively LEASE, KEEPALIVE, METADATA_PUSH, we break the ordering above per stream...
4) ... Should we make it clear that per stream is freely prioritised by the client and sender.  e.g. rsocket-java could support an API to bump the priority of the stream outside the spec.  This maybe what the section below is meant to convey.

But overall, I think this change functionally makes sense, since you definitely want to prioritise KEEPALIVES over a large video stream of effectively infinite PAYLOAD frames etc.


> 
> QoS and Prioritization
> 
> Quality of Service and Prioritization of streams are considered application or network layer concerns and are better dealt with at those layers. The metadata capabilities, including METADATA_PUSH, are tools that applications can use for effective prioritization. DiffServ via IP QoS are best handled by the underlying network layer protocols.

**Comment by OlegDokuka** [comment]
1) Agree
2) True
3) Not sure. Since the order of All the packets within the logical stream are unchanged and Stream ID 0 packets have no direct relation to a logical stream
4) 
5) I think soo

**Comment by OlegDokuka** [comment]
#280 solved by
